#!/bin/bash

clear 
echo '###############################################################################################'
echo ':::::::::: Arch Linux packages syncing script generated by Marlonlom :::::::::: '

paru_path=`which paru`
if [[ -z "$paru_path" ]]; then
  echo ":::::::::: Package (paru) path not found. Installing it using pacman ..."
  sudo pacman -S paru
  echo ':::::::::: Package (paru) installed, try executing this file again for mirrorlist syncing ...'
fi 

echo ":::::::::: Updating repository lists ..."
paru -Syu

echo ':::::::::: Arch Linux packages syncing script ended :::::::::: '
echo '###############################################################################################'

