#!/bin/bash

os=`cat /etc/*-release | grep "PRETTY_NAME" | sed 's/PRETTY_NAME=//g' | sed 's/"//g'`
if [[ "$os" != "Arch Linux" ]]; then
  echo "(X) Not running the script inside Archlinux. exiting ..."
  exit 1
fi

if [ `whoami` != root ]; then
  echo "(X) Please run this script as root or using sudo."
  exit 1
fi

clear 
echo '###############################################################################################'
echo ':::::::::: Arch Linux mirrorlist syncing script generated by Marlonlom :::::::::: '

reflector_path=`which reflector`
if [[ -z "$reflector_path" ]]; then
  echo ":::::::::: Package (reflector) path not found. Installing it using pacman ..."
  sudo pacman -S reflector rsync curl
  echo ':::::::::: Package (reflector) installed, try executing this file again for mirrorlist syncing ...'
fi 

echo ":::::::::: Creating backup from default mirror list file ..."
sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak  

echo ":::::::::: Using reflector for retrieving the most up-to-date 10 https mirrors that support ipv4, sorted by download rate, and saving it to /etc/pacman.d/mirrorlist ..."
sudo reflector --verbose --ipv4 -f 10 --protocol https --latest 10 --sort rate --save /etc/pacman.d/mirrorlist

echo ":::::::::: Verifying /etc/pacman.d/mirrorlist file ..."
cat /etc/pacman.d/mirrorlist

echo ":::::::::: Updating repository lists ..."
sudo pacman -Syu

echo ':::::::::: Arch Linux mirrorlist syncing script ended :::::::::: '
echo '###############################################################################################'

